# Generated by Django 3.2.22 on 2023-10-30 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('obName', models.CharField(max_length=200)),
                ('job', models.CharField(max_length=200)),
                ('summary', models.TextField(default='')),
                ('effect', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('logoImages', models.TextField(default='')),
                ('backgroundImages', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('github', models.CharField(default='', max_length=200)),
                ('isOB', models.BooleanField(default=False)),
                ('currentCoin', models.IntegerField(default=0)),
                ('sumCoin', models.IntegerField(default=0)),
                ('email', models.CharField(default='', max_length=200)),
                ('address', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('country', models.CharField(default='', max_length=200)),
                ('postalCode', models.TextField(default='', max_length=200)),
                ('aboutMe', models.TextField(default='', max_length=200)),
                ('plantName', models.TextField(default='애랑이')),
                ('plantExp', models.IntegerField(default=0)),
                ('plantRebirth', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=100)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoardLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='BoardImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='board')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member'),
        ),
    ]
