# Generated by Django 3.2.22 on 2023-10-30 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c_shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardimages',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardlike',
            name='board',
        ),
        migrations.RemoveField(
            model_name='boardlike',
            name='member',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projectimages',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectlike',
            name='member',
        ),
        migrations.RemoveField(
            model_name='projectlike',
            name='project',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardImages',
        ),
        migrations.DeleteModel(
            name='BoardLike',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.DeleteModel(
            name='ProjectLike',
        ),
    ]
