# Generated by Django 3.2.22 on 2023-10-30 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('c_shop', '0002_auto_20231030_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('link', models.CharField(max_length=400)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('team', models.CharField(max_length=100)),
                ('summary', models.TextField(default='')),
                ('content', models.TextField(default='')),
                ('category', models.IntegerField()),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='project')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.project')),
            ],
        ),
        migrations.CreateModel(
            name='BoardLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.member')),
            ],
        ),
        migrations.CreateModel(
            name='BoardImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='board')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='c_shop.board')),
            ],
        ),
    ]
