# Generated by Django 3.2.22 on 2023-10-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_shop', '0003_board_boardimages_boardlike_project_projectimages_projectlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='link',
            field=models.CharField(default='', max_length=400),
        ),
    ]
