# Generated by Django 3.2.22 on 2023-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c_shop', '0005_alter_projectimages_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teammate',
            field=models.CharField(default='', max_length=200),
        ),
    ]
